<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
	  <AssemblyVersion>1.0.*</AssemblyVersion>
	  <Deterministic>false</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;7035</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;7035</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\Static\locations.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\Static\keywords.txt" />
    <EmbeddedResource Include="Data\Static\locations.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.BrowserAPI" Version="0.15.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.8" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.8" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.8" />
    <PackageReference Include="TG.Blazor.IndexedDB" Version="1.5.0-preview" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Ox.SleepingGods.Exceptions" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\data\" />
  </ItemGroup>

</Project>
